[mqtt]
broker_ip = "134.130.172.253"
broker_port = 1883
client_name = "mqtt2postgres"
# optional
keep_alive_seconds = 5
# optional - recommended to increase when using JSON payloads
max_packet_size = 10000

[postgres]
connection_string = "postgresql://postgres:postgres@localhost:5432/mqtt2postgres"

[[topics.subscribe]]
topic = "#"

# [[topics.subscribe]]
# topic = "zigbee2mqtt/#"

# [[topics.subscribe]]
# topic = "awtrix/eceb30/#"

[[topics.ignore]]
topic = "homeassistant/#"

[[topics.ignore]]
topic = "+/broker/#"