version: "2"

services:
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mqtt2postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mqtt2postgres"]
      interval: 1s
      timeout: 5s
      retries: 10