edition = "2021"
max_width = 90
newline_style = "Unix"
unstable_features = true

tab_spaces = 4

match_block_trailing_comma = true
trailing_comma = "Never"

imports_granularity = "Crate"
#group_imports = "One"

format_code_in_doc_comments = true
format_macro_matchers = true

use_field_init_shorthand = true
use_try_shorthand = true

condense_wildcard_suffixes = true

overflow_delimited_expr = true

spaces_around_ranges = true