apiVersion: 1

prune: true

datasources:
  - name: Postgres
    type: postgres
    uid: pgds
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: 'postgres'
    jsonData:
      database: mqtt2postgres
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      timescaledb: true
